### ISSUE TITLE
Checklists Bug

### ISSUE THREAD

**Issue by TheStrangeKat** [gizmomogwai/org-kanban#14]
There seems to be a problem with including a checklist tracking component in a heading.
i.e.
```
* todo Heading [2/4]
 - [x] item 1
 - [x] item 2
 - [ ] item 3
 - [ ] item 4
```

Will not display correctly in the kanban board.

**Comment by gizmomogwai** [comment]
can you give me a small complete example? it looks your
   
    * todo Heading [2/4]


is using custom todo keywords?

**Comment by gizmomogwai** [comment]
e.g.

    * TODO test [/]
    ** TODO test1
    ** TODO test2
    #+BEGIN: kanban
    #+END:

**Comment by TheStrangeKat** [comment]
Forgot to insert the first section as code! Corrected.

Sorry, yes, I do have custom TODO keywords. Does this break it?
`(setq org-todo-keywords
  '((sequence "TODO" "WIP" "|" "DONE")))
`

This is what it ends up looking like:

```
* TODO Heading One
* TODO Heading Two
* TODO Heading Three with list [1/3]
- [X] item 1
- [ ] item 2
- [ ] item 3

#+BEGIN: kanban 
| TODO                                                             | WIP | DONE |
|------------------------------------------------------------------+-----+------|
| [Heading One]                                                    |     |      |
| [Heading Two]                                                    |     |      |
| [[Heading Three with list [1/3]][Heading Three with list [1/3]]] |     |      |
#+END:
```

**Comment by gizmomogwai** [comment]
thanks for the example. i think its more connected to
https://stackoverflow.com/questions/27284913/how-to-escape-square-bracket-in-org-mode-links
thanks for pointing that out ... 
i might have to replace the link itself by something that does not contain the [] and the linktext with something else e.g. {} instead of [] or finding some similar looking unicode charachter ...

the builtin org-mode function org-make-link-string also does not work for me as it produces links, that do not lead to your real heading.

**Comment by TheStrangeKat** [comment]
The curly brackets look like it might be the best solution. It seems to be the way the "org-store-link" function works. When storing the link like that and then inserting it again, the link ends up looking like:

`Heading Three with list {1/3}`

**Comment by gizmomogwai** [comment]
i pushed a fix, should be available on melpa after a while.

**Comment by gizmomogwai** [comment]
org-kanban/version should print 0.4.10.

**Comment by TheStrangeKat** [comment]
Excellent, this looks a lot better. Thanks :)
