### ISSUE TITLE
TODO Items with URLs are not handled correctly

### ISSUE THREAD

**Issue by veselinovic** [gizmomogwai/org-kanban#20]
```
#+BEGIN: kanban
| TODO                                  | DOING | WAITING | DONE |
|---------------------------------------+-------+---------+------|
| [[][{{https://github.com/}{github}}]] |       |         |      |
#+END:

* TODO [[https://github.com/][github]]
```

org-kanban Version: 20190802.2107 
installed with melpa under Mac with GNU Emacs 26.2

**Comment by gizmomogwai** [comment]
Thanks for the bugreport.

I can solve this, by replacing the heading (which is an org link with link + title) with the title in the org-kanban table.
The only problem with this is, that if you click on the title in the table, it will not jump to the todo heading, but ask to create this todo item (because there is at this moment no todo item with the title as heading). the only way for you to work around this would be, to add a custom_id to the TODO item. org-kanban then would the prefer to use the custom_id as the link anchor instead of the title.

Would this be an acceptable solution for you?

**Comment by veselinovic** [comment]
This solution would work for me. Thank's a lot
