### ISSUE TITLE
[Bug]?: Following links within Kanban tables entries gives "No match" though file exists

### ISSUE THREAD

**Issue by wakatara** [gizmomogwai/org-kanban#30]
Inside the dynamic block, file links of the type: 

`[[file:gtd-tools-shootout.org][GTD Tools Shootout]]` when C-c C-o to follow the link to the resulting file, yield a "No match - create this as a new heading? (yes or no)" despite the fact the file exists and can also be followed in the `TODO` level item the Kanban block uses as "source".

In this case, TODO line items like `* Idea [[file:gtd-tools-shootout.org][GTD Tools Shootout]`

Looks like a big as the second buffer open up, but then for some reason it's unable to find the file.

If it helps diagnose I can give you the test file I'm using.

**Comment by gizmomogwai** [comment]
thanks for the report ... i think there is a misunderstanding.
normally org-kanban collects optionally todos from several files (and by todos it means that it jumps to the todo there).
in your case the link that is created is the link to the right org file, but then its trying to jumpt to `* Idea GTD Tools Shootout`. Not sure if this is a bug or not ... For sure its not what you want :)

**Comment by wakatara** [comment]
Hehe... Understood. 

Could there be an option where it follows the link in the text rather than the Todo in the document? Would be *super* handy. And allows all sorts of nice kanban goodness like linking to other files (which is becoming dman easy with org-roam).

**Comment by gizmomogwai** [comment]
How would the complete scenario look like?

**Comment by gizmomogwai** [comment]
I thought a little bit more about your usecase, but I still do not quite get it.
What confuses me is, how you want to change the state of one of your ideas.
e.g. from idea, to in-progress to published. I guess from what i take from your issue that you would take the line with the link to the org file and put it into another section.

What I could think of is a different organization:
You could have one org-kanban table in a separate file for overview and use :scope (file1.org file2.org gtd-tools-shootout.org) then in gts-tools-shootout.org you could have one top level heading e.g. * Idea Shootout that will be listed in the kanban table + that also represents the state ... e.g. you would move the item itself to a new state if appropriate.

the overview.org file would only be a overview thingy, that is kind of automatically created instead of manually maintained ... you only need to put all the files you want to have searched into the :scope parameter. i also think that very early on ideas do not deserve a whole file, so you could have a file that collects several of them ...

tell me what you think.

**Comment by gizmomogwai** [comment]
Is this still something you are considering?
