### ISSUE TITLE
Feature request: create kanban in empty org-mode file, point to another org-mode file

### ISSUE THREAD

**Issue by Trevoke** [gizmomogwai/org-kanban#4]
For instance:

```
#+BEGIN: kanban :file ~/org/chores.org
#+END:
```

Would create a kanban table based on what's in `chores.org`.

**Comment by gizmomogwai** [comment]
Another great feature request. Will have to look into the org api to see, if i can easily implement this!

**Comment by gizmomogwai** [comment]
to get the parameter use (plist-get params :file)

**Comment by gizmomogwai** [comment]
ok .. last one ... 
i am not sure, if this is soo simple ... i think we want something like org-agenda, but as a kanban board.
another question is, what happens, if you store the kanban board, should hte other file/files also be saved?

**Comment by gizmomogwai** [comment]
Ok ... i understand ... i meant just like agenda-files in which you say from where you want to collect your todos ...

so you would edit the other file and safe it automatically, if interacting with the kanban board?

i asked around in the org-mode irc, because i dont know the api that well (and it seems, there is no api to get the todos of a file) .. i will try quickly to open the file in another buffer and use my current method, perhaps this works ... 
also the links to the todos would get a little bit more complicated :/ .. lets see ...

btw. ... how are you using this plugin? with the melpa package or from source?

**Comment by gizmomogwai** [comment]
@Trevoke please have a look ... test1.org shows how to use it.
at the moment the "other" file is not automatically stored, and i guess the table is not right, if different todo-keywords are used in the files.

**Comment by gizmomogwai** [comment]
I pushed a new version to master ... with this I am quite happy ...
it collects all different org keywords from all files and puts those to the table.
the org-items can still be shifted in the kanban board (but only to the keywords, that are defined for them). if you have everywhere the samekeywords or use the default ones, this should not matter, but i wanted to have a generic solution...
